"""Representative terrain parameters used by the preview script.

These values are intentionally separate from training configs.  They should
make each terrain visually recognizable at the default preview difficulty.
"""

ABSTRACT_CFG_NAMES = {"HfRoughTerrainCfg", "MeshRoughTerrainCfg"}
"""Terrain cfg classes exported by the package but not meant to be previewed directly."""


PREVIEW_CASES: dict[str, dict] = {
    "HfFlatRoughTerrainCfg": {
        "noise_range": (-0.04, 0.04),
        "noise_step": 0.01,
        "downsampled_scale": 0.2,
        "apply_roughness": 1.0,
        "roughness_type": "difficulty",
    },
    "HfPyramidSlopedRoughTerrainCfg": {
        "slope_range": (0.0, 0.6),
        "center_platform_width": 3.0,
        "noise_range": (-0.02, 0.08),
        "noise_step": 0.01,
        "apply_roughness": 1.0,
        "roughness_type": "difficulty",
        "apply_poles": 1.0,
        "num_poles_range": (3, 5),
        "border_width": 0.1,
    },
    "HfInvertedPyramidSlopedRoughTerrainCfg": {
        "slope_range": (0.0, 0.6),
        "center_platform_width": 3.0,
        "noise_range": (-0.02, 0.08),
        "noise_step": 0.01,
        "apply_roughness": 1.0,
        "roughness_type": "difficulty",
        "border_width": 0.1,
    },
    "HfDiscreteObstaclesTerrainCfg": {
        "obstacle_width_range": (1.0, 2.0),
        "obstacle_height_range": (0.05, 0.25),
        "num_obstacles": 15,
        "center_platform_width": 3.0,
        "border_width": 0.1,
    },
    "HfGapTerrainCfg": {
        "gap_width_range": (0.1, 0.9),
        "gap_depth_range": (1.0, 3.0),
        "center_platform_width_range": (3.0, 4.0),
        "platform_height_range": (-0.1, 0.1),
        "border_width": 0.1,
    },
    "HfDoubleGapTerrainCfg": {
        "gap_width_range": (0.2, 0.6),
        "gap_depth_range": (0.5, 1.0),
        "gap_in_between_width_range": (0.8, 1.0),
        "center_platform_width_range": (3.0, 4.0),
        "platform_height_range": (-0.1, 0.1),
        "border_width": 0.1,
    },
    "HfStraightGapTerrainCfg": {
        "num_gaps_per_side_range": (2, 2),
        "gap_width_range": (0.2, 0.8),
        "gap_depth_range": (1.0, 3.0),
        "center_platform_width_range": (3.0, 4.0),
        "island_width_range": (0.6, 1.2),
        "island_y_offset_range": (-1.0, 1.0),
        "island_height_offset_range": (-0.1, 0.1),
        "center_platform_width_range": (3.0, 4.0),
        "border_width": 0.1,
    },
    "HfStraightClimbTerrainCfg": {
        "wall_height_range": (0.25, 0.70),
        "wall_width_range": (0.8, 1.2),
        "wall_length_range": (4.0, 8.0),
        "border_width": 0.1,
    },
    "MeshCorridorTerrainCfg": {
        "center_platform_width_range": (3.8, 4.2),
        "wall_height_range": (1.0, 1.0),
        "wall_width_range": (0.4, 0.8),
        "wall_spacing_range": (0.28, 0.32),
        "noise_range": (-0.03, 0.03),
        "noise_step": 0.01,
        "roughness_type": "fixed",
        "apply_roughness": 1.0,
        "border_width": 0.1,
    },
    "HfHurdleTerrainCfg": {
        "hurdle_width_range": (0.2, 0.5),
        "hurdle_height_range": (0.05, 0.25),
        "center_platform_width_range": (3.0, 4.0),
        "border_width": 0.1,
    },
    "HfPyramidStairsTerrainCfg": {
        "stair_height_range": (0.05, 0.22),
        "stair_width": 0.5,
        "center_platform_width": 3.0,
    },
    "HfInvertedPyramidStairsTerrainCfg": {
        "stair_height_range": (0.05, 0.22),
        "stair_width": 0.5,
        "center_platform_width": 3.0,
        "inverted": True,
    },
    "MeshPyramidStairsTerrainCfg": {
        "stair_height_range": (0.05, 0.22),
        "stair_width": 0.30,
        "center_platform_width": 3.0,
        "noise_range": (-0.04, 0.04),
        "noise_step": 0.01,
        "downsampled_scale": 0.2,
        "apply_roughness": 1.0,
        "roughness_type": "fixed",
    },
    "MeshFloatingPyramidStairsTerrainCfg": {
        "stair_height_range": (0.05, 0.22),
        "stair_width": 0.30,
        "stair_thickness": 0.04,
        "center_platform_width": (2.8, 3.2),
        "border_width": 0.25,
    },
    "MeshCircularDoorsTerrainCfg": {
        "inner_radius": 1.0,
        "inner_radius_noise_range": (-0.20, 0.20),
        "ring_spacing": 1.0,
        "ring_spacing_noise_range": (-0.15, 0.15),
        "wall_height_range": (1.0, 1.8),
        "wall_arc_length": 1.5,
        "wall_arc_length_noise_range": (-0.30, 0.30),
        "door_width": 1.0,
        "door_width_noise_range": (-0.20, 0.20),
    },
    "MeshRandomCeilingObstaclesTerrainCfg": {
        "block_num_range": (8, 18),
        "block_width_range": (0.8, 1.6),
        "block_thickness_range": (0.1, 0.25),
        "clearance_height_range": (1.0, 1.8),
        "center_clearance": 1.0,
    },
    "MeshHexSteppingStonesTerrainCfg": {
        "pillar_radius_range": (0.12, 0.22),
        "pillar_spacing_range": (0.45, 0.9),
        "pit_depth_range": (0.5, 1.0),
        "stone_height_noise_range": (-0.1, 0.1),
        "stone_height_noise_type": "difficulty",
        "cross_shape": False,
        "center_platform_width_range": (1.6, 2.0),
    },
    "MeshPillarForestTerrainCfg": {
        "pillar_count_range": (12, 28),
        "pillar_radius_range": (0.10, 0.20),
        "pillar_height_range": (0.5, 1.5),
        "pillar_clearance": 0.10,
        "center_clearance": 1.0,
    },
    "MeshRingPlatformsTerrainCfg": {
        "center_platform_width_range": (0.9, 1.5),
        "ring_width": 0.35,
        "ring_gap_range": (0.4, 0.8),
        "ring_platform_height_range": (0.1, 0.35),
    },
    "MeshMazeTerrainCfg": {
        "cell_size": 1.5,
        "wall_thickness": 0.15,
        "wall_height_range": (0.8, 1.8),
    },
    "MeshInvertedFloatingPyramidStairsTerrainCfg": {
        "stair_height_range": (0.05, 0.22),
        "stair_width": 0.30,
        "stair_thickness": 0.04,
        "center_platform_width": (2.8, 3.2),
        "border_width": 0.25,
        "inverted": True,
        "extend_center_platform_under_stairs": True,
    },
    "MeshInvertedPyramidStairsTerrainCfg": {
        "stair_height_range": (0.05, 0.22),
        "stair_width": 0.30,
        "center_platform_width": 3.0,
        "inverted": True,
        "noise_range": (-0.04, 0.04),
        "noise_step": 0.01,
        "downsampled_scale": 0.2,
        "apply_roughness": 1.0,
        "roughness_type": "fixed",
    },
    "MeshHurdleTerrainCfg": {
        "num_hurdles_per_side_range": (2, 3),
        "hurdle_width_range": (0.2, 0.5),
        "hurdle_height_range": (0.05, 0.25),
        "spacing_range": (0.4, 1.0),
        "center_platform_width_range": (2.0, 3.0),
    },
    "MeshStraightGapTerrainCfg": {
        "num_gaps_per_side_range": (2, 2),
        "gap_width_range": (0.2, 0.8),
        "gap_depth_range": (1.0, 3.0),
        "center_platform_width_range": (3.0, 4.0),
        "island_width_range": (0.6, 1.2),
        "island_y_offset_range": (-1.0, 1.0),
        "island_height_offset_range": (-0.1, 0.1),
    },
    "MeshStraightStairsTerrainCfg": {
        "stair_width": 0.3,
        "stair_width_noise_range": (-0.02, 0.02),
        "stair_height_range": (0.05, 0.22),
        "stair_length_range": (2.0, 6.0),
        "num_stairs_range": (2, 7),
        "center_platform_width_range": (3.0, 4.0),
    },
    "MeshInvertedStraightStairsTerrainCfg": {
        "stair_width": 0.3,
        "stair_width_noise_range": (-0.02, 0.02),
        "stair_height_range": (0.05, 0.22),
        "stair_length_range": (2.0, 6.0),
        "num_stairs_range": (2, 7),
        "center_platform_width_range": (3.0, 4.0),
    },
    "MeshRepeatedBoxesTerrainCfg": {
        "num_objects_range": (12, 18),
        "num_objects_type": "difficulty",
        "box_height_range": (0.1, 0.3),
        "box_length_range": (0.3, 0.8),
        "box_width_range": (0.3, 0.8),
        "center_platform_width": 3.0,
    },
}
"""Concrete preview kwargs keyed by exported terrain cfg class name."""
