# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
# Original code is licensed under BSD-3-Clause.
#
# Copyright (c) 2025-2026, The Loco Lab Project Developers.
# All rights reserved.
# Modifications are licensed under BSD-3-Clause.

"""Configuration for custom terrains."""

import locolab.utils.terrains.locolab_terrains as locolab_terrain_gen
from locolab.utils.terrains import TerrainGeneratorCfg

"""Flat terrain with small geometric roughness."""
FLAT_ROUGH_TERRAINS_CFG = TerrainGeneratorCfg(
    curriculum=False,
    size=(8.0, 8.0),
    border_width=20.0,
    num_rows=5,
    num_cols=5,
    horizontal_scale=0.1,
    vertical_scale=0.01,
    slope_threshold=0.75,
    use_cache=False,
    sub_terrains={
        "flat_rough": locolab_terrain_gen.HfFlatRoughTerrainCfg(
            proportion=1.0,
            noise_range=(-0.08, 0.08),
            noise_step=0.01,
            downsampled_scale=0.1,
            roughness_type="random",
            roughness_strengths=(0.25, 0.50, 0.75, 1.0),  # samples uniformly from these strengths
            apply_roughness=0.9,  # probability of applying roughness to a generated sub-terrain
        ),
    },
)

"""Rough terrains configuration - for blind locomotion"""
ROUGH_TERRAINS_CFG = TerrainGeneratorCfg(
    curriculum=True,
    size=(8.0, 8.0),
    border_width=20.0,
    num_rows=10,
    num_cols=20,
    horizontal_scale=0.1,
    vertical_scale=0.01,
    slope_threshold=0.75,
    use_cache=False,
    sub_terrains={
        "stairs_30": locolab_terrain_gen.MeshPyramidStairsTerrainCfg(
            proportion=0.20,
            stair_height_range=(0.02, 0.22),
            stair_width=0.30,
            center_platform_width=3.0,
            border_width=0.5,
            roughness_type="random",
            noise_range=(-0.03, 0.03),
            roughness_strengths=(0.50, 1.0),
            apply_roughness=0.5,
            holes=False,
        ),
        "stairs_30_inv": locolab_terrain_gen.MeshInvertedPyramidStairsTerrainCfg(
            proportion=0.30,
            stair_height_range=(0.02, 0.22),
            stair_width=0.30,
            center_platform_width=3.0,
            border_width=0.5,
            roughness_type="random",
            noise_range=(-0.03, 0.03),
            roughness_strengths=(0.50, 1.0),
            apply_roughness=0.5,
            holes=False,
        ),
        #  "flat_rough": locolab_terrain_gen.HfFlatRoughTerrainCfg(
        #      proportion=0.1,
        #      noise_range=(-0.06, 0.06),
        #      noise_step=0.01,
        #      downsampled_scale=0.1,
        #      roughness_type="random",
        #      roughness_strengths=(0.25, 0.50, 0.75, 1.0),  # samples uniformly from these strengths
        #      apply_roughness=0.9,  # probability of applying roughness to a generated sub-terrain
        #  ),
        "slope": locolab_terrain_gen.HfPyramidSlopedRoughTerrainCfg(
            proportion=0.15,
            slope_range=(0.0, 0.45),
            center_platform_width=2.0,
            noise_range=(-0.08, 0.08),
            noise_step=0.01,
            apply_roughness=0.9,
            roughness_type="random",
            roughness_strengths=(0.4, 0.8, 0.8, 1.0),
            border_width=0.10,
        ),
        "slope_inv": locolab_terrain_gen.HfInvertedPyramidSlopedRoughTerrainCfg(
            proportion=0.15,
            slope_range=(0.0, 0.45),
            center_platform_width=3.0,
            noise_range=(-0.08, 0.08),
            noise_step=0.01,
            apply_roughness=0.9,
            roughness_type="random",
            roughness_strengths=(0.4, 0.8, 0.8, 1.0),
            border_width=0.10,
        ),
        "discrete": locolab_terrain_gen.HfDiscreteObstaclesTerrainCfg(
            proportion=0.2,
            obstacle_width_range=(1.0, 2.5),
            obstacle_height_range=(0.02, 0.22),
            num_obstacles=20,
            center_platform_width=3.0,
            noise_range=(-0.05, 0.05),
            noise_step=0.01,
            apply_roughness=0.8,
            roughness_type="random",
            border_width=0.10,
        ),
    },
)

"""Rough parkour terrains configuration - for perceptive locomotion"""
# This is only a template, which is a guideline for users to create their own parkour terrains.
PARKOUR_TERRAINS_CFG = TerrainGeneratorCfg(
    curriculum=True,
    size=(8.0, 8.0),
    border_width=20.0,
    num_rows=10,
    num_cols=20,
    horizontal_scale=0.1,
    vertical_scale=0.01,
    slope_threshold=0.75,
    use_cache=False,
    sub_terrains={
        "stairs_30": locolab_terrain_gen.MeshPyramidStairsTerrainCfg(
            proportion=0.05,
            stair_height_range=(0.10, 0.30),
            stair_width=0.30,
            stair_width_noise_range=(-0.05, 0.05),
            center_platform_width=3.0,
            border_width=0.5,
            apply_poles=0.5,
            num_poles_range=(2, 8),
            holes=False,
        ),
        "stairs_30_inv": locolab_terrain_gen.MeshInvertedPyramidStairsTerrainCfg(
            proportion=0.05,
            stair_height_range=(0.10, 0.30),
            stair_width=0.30,
            stair_width_noise_range=(-0.05, 0.05),
            center_platform_width=3.0,
            border_width=0.5,
            apply_poles=0.5,
            num_poles_range=(2, 8),
            holes=False,
        ),
        "floating_stairs": locolab_terrain_gen.MeshFloatingPyramidStairsTerrainCfg(
           proportion=0.05,
           stair_height_range=(0.10, 0.30),
           stair_width=0.30,
           stair_width_noise_range=(-0.05, 0.05),
           stair_thickness=0.05,
           center_platform_width=(1.5, 2.5),
           border_width=0.5,
           stair_type="random",
        ),
        "floating_stairs_inv": locolab_terrain_gen.MeshInvertedFloatingPyramidStairsTerrainCfg(
           proportion=0.05,
           stair_height_range=(0.10, 0.30),
           stair_width=0.30,
           stair_width_noise_range=(-0.05, 0.05),
           stair_thickness=0.05,
           center_platform_width=(1.5, 2.5),
           border_width=0.5,
           stair_type="random",
           extend_center_platform_under_stairs=True,
        ),
        #  "straight_stairs": locolab_terrain_gen.MeshStraightStairsTerrainCfg(
        #      proportion=0.05,
        #      stair_width=0.30,
        #      stair_width_noise_range=(-0.05, 0.10),
        #      stair_height_range=(0.10, 0.30),
        #      stair_length_range=(1.0, 3.0),
        #      num_stairs_range=(6, 8),
        #      center_platform_width_range=(2.0, 3.0),
        #  ),
        #  "straight_stairs_inv": locolab_terrain_gen.MeshInvertedStraightStairsTerrainCfg(
        #      proportion=0.05,
        #      stair_width=0.30,
        #      stair_width_noise_range=(-0.05, 0.10),
        #      stair_height_range=(0.10, 0.30),
        #      stair_length_range=(1.0, 3.0),
        #      num_stairs_range=(6, 8),
        #      center_platform_width_range=(2.0, 3.0),
        #  ),
        "slope": locolab_terrain_gen.HfPyramidSlopedRoughTerrainCfg(
            proportion=0.05,
            slope_range=(0.0, 0.45),
            center_platform_width=2.0,
            noise_range=(-0.08, 0.08),
            noise_step=0.01,
            apply_roughness=0.8,
            roughness_type="random",
            apply_poles=0.6,
            num_poles_range=(2, 8),
            border_width=0.10,
        ),
        "slope_inv": locolab_terrain_gen.HfInvertedPyramidSlopedRoughTerrainCfg(
            proportion=0.05,
            slope_range=(0.0, 0.45),
            center_platform_width=3.0,
            noise_range=(-0.08, 0.08),
            noise_step=0.01,
            apply_roughness=0.8,
            roughness_type="random",
            apply_poles=0.6,
            num_poles_range=(2, 8),
            border_width=0.10,
        ),
        "discrete": locolab_terrain_gen.HfDiscreteObstaclesTerrainCfg(
            proportion=0.05,
            obstacle_width_range=(1.0, 2.0),
            obstacle_height_range=(0.10, 0.35),
            num_obstacles=20,
            center_platform_width=3.0,
            noise_range=(-0.05, 0.05),
            noise_step=0.01,
            apply_roughness=0.8,
            roughness_type="random",
            border_width=0.10,
        ),
        "box": locolab_terrain_gen.MeshRepeatedBoxesTerrainCfg(
            proportion=0.05,
            center_platform_width=2.0,
            num_objects_range=(15, 30),
            num_objects_type="random",
            box_height_range=(0.10, 0.35),
            box_length_range=(0.30, 1.0),
            box_width_range=(0.30, 1.0),
            angle_range=(0.0, 15.0),
            angle_type="random",
            angle_degrees=True,
            abs_height_noise=(-0.08, 0.08),
            rel_height_noise=(1.0, 2.0),
        ),
        # "gap": locolab_terrain_gen.HfGapTerrainCfg(
        #     proportion=0.15,
        #     gap_width_range=(0.10, 0.70),
        #     gap_depth_range=(1.0, 2.5),
        #     gap_depth_type="random",
        #     center_platform_width_range=(2.0, 4.0),
        #     platform_height_range=(-0.10, 0.10),
        # ),
        # "double_gap": locolab_terrain_gen.HfDoubleGapTerrainCfg(
        #     proportion=0.1,
        #     gap_width_range=(0.10, 0.50),
        #     gap_depth_range=(1.0, 2.5),
        #     gap_depth_type="random",
        #     gap_in_between_width_range=(0.5, 1.5),
        #     center_platform_width_range=(2.0, 3.0),
        #     platform_height_range=(-0.10, 0.10),
        # ),
        # "gap": locolab_terrain_gen.HfStraightGapTerrainCfg(
        "gap": locolab_terrain_gen.MeshStraightGapTerrainCfg(
            proportion=0.05,
            gap_width_range=(0.10, 0.80),
            gap_depth_range=(1.0, 2.5),
            gap_depth_type="random",
            island_width_range=(1.0, 2.0),
            island_y_offset_range=(-0.5, 0.5),
            center_platform_width_range=(2.0, 3.0),
            noise_range=(-0.04, 0.04),
            noise_step=0.01,
            roughness_type="random",
            roughness_strengths=(0.4, 0.7, 1.0),  # samples uniformly from these strengths
            apply_roughness=0.8,
        ),
        "climb": locolab_terrain_gen.HfStraightClimbTerrainCfg(
            proportion=0.05,
            wall_height_range=(0.25, 0.70),
            wall_width_range=(0.8, 1.5),
            wall_length_range=(3.0, 6.0),
            noise_range=(-0.03, 0.03),
            noise_step=0.01,
            roughness_type="random",
            roughness_strengths=(0.4, 0.7, 1.0),
            apply_roughness=0.8,
            border_width=0.10,
        ),
        "corridor": locolab_terrain_gen.MeshCorridorTerrainCfg(
            proportion=0.05,
            center_platform_width_range=(2.0, 4.0),
            wall_height_range=(1.0, 1.5),
            wall_width_range=(0.8, 1.6),
            wall_spacing_range=(0.30, 0.60),
            noise_range=(-0.05, 0.05),
            noise_step=0.01,
            roughness_type="random",
            roughness_strengths=(0.4, 0.7, 1.0),
            apply_roughness=0.8,
            border_width=0.10,
        ),
        "circular_doors": locolab_terrain_gen.MeshCircularDoorsTerrainCfg(
            proportion=0.05,
            inner_radius=1.0,
            inner_radius_noise_range=(-0.25, 0.25),
            ring_spacing=1.0,
            ring_spacing_noise_range=(-0.25, 0.5),
            wall_height_range=(1.0, 2.0),
            wall_arc_length=1.5,
            wall_arc_length_noise_range=(-0.25, 0.25),
            door_width=1.0,
            door_width_noise_range=(-0.25, 0.25),
            border_width=0.25,
        ),
        "ceiling": locolab_terrain_gen.MeshRandomCeilingObstaclesTerrainCfg(
            proportion=0.05,
            block_num_range=(6, 12),
            block_width_range=(0.5, 1.5),
            block_thickness_range=(0.1, 0.3),
            clearance_height_range=(0.5, 1.5),
        ),
        "hex_stepping_stones": locolab_terrain_gen.MeshHexSteppingStonesTerrainCfg(
            proportion=0.05,
            pillar_radius_range=(0.15, 0.20),
            pillar_spacing_range=(0.40, 0.80),
            pit_depth_range=(0.5, 1.0),
            stone_height_noise_range=(-0.08, 0.08),
            stone_height_noise_type="random",
            cross_shape=True,
            center_platform_width_range=(1.2, 2.5),
            border_width=0.10,
        ),
        "pillar_forest": locolab_terrain_gen.MeshPillarForestTerrainCfg(
            proportion=0.05,
            pillar_count_range=(12, 28),
            pillar_radius_range=(0.10, 0.20),
            pillar_height_range=(0.5, 1.5),
            pillar_clearance=0.20,
            center_clearance=1.0,
        ),
        "ring_platforms": locolab_terrain_gen.MeshRingPlatformsTerrainCfg(  # ring platforms terrain is similar to hurdle terrain
            proportion=0.05,
            center_platform_width_range=(1.5, 2.0),
            ring_width=0.35,
            ring_gap_range=(0.4, 0.8),
            ring_platform_height_range=(0.10, 0.50),
            border_width=0.5,
        ),
        "maze": locolab_terrain_gen.MeshMazeTerrainCfg(  # maze is closed in subterrain, do not apply to naive velocity sampling command
            proportion=0.05,
            cell_size=1.5,
            wall_thickness=0.15,
            wall_height_range=(0.5, 1.5),
        ),
        "stairs_high": locolab_terrain_gen.HfPyramidStairsTerrainCfg(
            proportion=0.05,
            stair_height_range=(0.15, 0.50),
            stair_width=1.25,
            stair_width_noise_range=(-0.25, 0.25),
            center_platform_width=2.0,
            noise_range=(-0.05, 0.05),
            noise_step=0.01,
            roughness_type="random",
            roughness_strengths=(0.4, 0.6, 0.8, 1.0),  # samples uniformly from these strengths
            apply_roughness=0.8,
        ),
        "stairs_high_inv": locolab_terrain_gen.HfInvertedPyramidStairsTerrainCfg(
            proportion=0.05,
            stair_height_range=(0.15, 0.50),
            stair_width=1.25,
            stair_width_noise_range=(-0.25, 0.25),
            center_platform_width=2.0,
            noise_range=(-0.05, 0.05),
            noise_step=0.01,
            roughness_type="random",
            roughness_strengths=(0.4, 0.6, 0.8, 1.0),  # samples uniformly from these strengths
            apply_roughness=0.8,
        ),
        "hurdle": locolab_terrain_gen.MeshHurdleTerrainCfg(
            proportion=0.05,
            hurdle_width_range=(0.1, 0.4),
            hurdle_height_range=(0.15, 0.45),
            spacing_range=(1.0, 1.5),
            center_platform_width_range=(1.5, 2.0),
        ),
    },
)
